[package]
name = "mm2rs"
version = "0.1.0"
edition = "2021"

[dependencies]
memmap2 = "0.9"
thiserror = "1.0"
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"
rayon = "1.8"
noodles-fasta = { git = "https://github.com/zaeleus/noodles" }

[dev-dependencies]
assert_cmd = "2.0"
